"""Local keyword scope rules; no trained model or probability calibration."""
import re
import time
import unicodedata
from typing import Any, Dict

DOMAIN_RULES = {'MISMATCH_INQUIRY': {'keywords': ['錯配',
                                   '預警',
                                   '缺工',
                                   '短缺',
                                   '過剩',
                                   '失衡',
                                   '訊號',
                                   '信號',
                                   '強度',
                                   '風險',
                                   '燈號',
                                   '供需',
                                   '不足'],
                      'weight': 1.2},
 'INDUSTRY_DYNAMICS': {'keywords': ['產業',
                                    '擴張',
                                    '動能',
                                    '新設',
                                    '設立',
                                    '設立率',
                                    '資本',
                                    '增資',
                                    '解散',
                                    '歇業',
                                    '存量',
                                    '精密機械',
                                    '智慧製造',
                                    '資訊軟體',
                                    '數位科技',
                                    '半導體',
                                    '綠能',
                                    '生技醫療',
                                    '金融服務',
                                    '國際貿易',
                                    '現代物流',
                                    '文創'],
                       'weight': 1.1},
 'SPATIAL_DEMAND': {'keywords': ['行政區',
                                 '西屯',
                                 '南屯',
                                 '北屯',
                                 '潭子',
                                 '大雅',
                                 '豐原',
                                 '梧棲',
                                 '烏日',
                                 '大里',
                                 '太平',
                                 '台中',
                                 '臺中',
                                 '空間',
                                 '聚落',
                                 '園區',
                                 '工業區'],
                    'weight': 1.1},
 'DEMOGRAPHIC_CLIFF': {'keywords': ['人口',
                                    '少子化',
                                    '18歲',
                                    '117',
                                    '虎年',
                                    '生源',
                                    '新生推估',
                                    '出生',
                                    '谷底',
                                    '海嘯',
                                    '縮減',
                                    '驟減'],
                       'weight': 1.2},
 'COMPANY_VERIFICATION': {'keywords': ['公司',
                                       '統編',
                                       '企業',
                                       '資本額',
                                       '核准設立',
                                       '登記',
                                       '台積電',
                                       '友達',
                                       '大立光',
                                       '上銀',
                                       '查證',
                                       '核對',
                                       '統編查證'],
                          'weight': 1.3},
 'TALENT_SUPPLY': {'keywords': ['招生',
                                '新生',
                                '註冊率',
                                '在學',
                                '系所',
                                '學系',
                                '學校',
                                '中科',
                                '大專',
                                '學生數',
                                '學年度',
                                '逢甲',
                                '中興',
                                '勤益',
                                '東海',
                                '靜宜',
                                '亞洲',
                                '朝陽',
                                '弘光',
                                '中臺',
                                '嶺東',
                                '僑光',
                                '商管',
                                '工學院',
                                '資工',
                                '機械',
                                '國貿',
                                '企管',
                                '生醫',
                                '財金',
                                '多媒體',
                                'ucan',
                                '職涯',
                                '人才',
                                '供給'],
                   'weight': 1.1},
 'HIRING_TREND': {'keywords': ['招募',
                               '招聘',
                               '徵才',
                               '職缺',
                               '人力需求',
                               '人力短缺',
                               '招人',
                               '求職者',
                               '應徵者',
                               '候選人',
                               '招工',
                               '只招',
                               '缺工',
                               'hiring',
                               'recruit',
                               'applicant',
                               'candidate',
                               'interview',
                               '擴廠',
                               '擴建',
                               '新廠',
                               '工廠',
                               '廠房',
                               '製造業',
                               '進廠',
                               '作業員',
                               '技術員',
                               '產線',
                               '人力',
                               '招人',
                               '招工',
                               '員工',
                               '面試',
                               '履歷',
                               '公平招募',
                               '招募流程',
                               '勞工',
                               '勞動',
                               '就業',
                               '就服法',
                               '歧視',
                               '職務',
                               '聘僱'],
                  'weight': 1.1},
 'OFFICIAL_DATA': {'keywords': ['官方資料', '公開資料', '政府資料', '官方數據', '投保薪資', '勞保', '就業通', 'gcis'],
                   'weight': 1.0}}

ENGLISH_DOMAIN = re.compile(r"\b(?:hir(?:e|ing)|recruit\w*|workforce|staff\w*|employee\w*|employment|labor|labour|vacanc\w*|applicant\w*|candidate\w*|manufactur\w*|official\s+data)\b", re.I)


class KeywordScopeGuard:
    """Conservative product routing heuristic, not a correctness/safety verdict."""
    version = "keyword-scope-v2"

    def evaluate(self, query: str) -> Dict[str, Any]:
        start = time.perf_counter()
        text = unicodedata.normalize("NFKC", query or "").strip().lower()
        scores = {category: sum(term in text for term in rule["keywords"]) * rule["weight"]
                  for category, rule in DOMAIN_RULES.items()}
        if ENGLISH_DOMAIN.search(text):
            scores["HIRING_TREND"] += 1
        if re.search(r"\b\d{8}\b", text):
            scores["COMPANY_VERIFICATION"] += 2.5
        category = max(scores, key=scores.get)
        score = scores[category]
        accepted = bool(text and score > 0)
        if not accepted:
            category = "EMPTY_QUERY" if not text else "UNRECOGNIZED_SCOPE"
        return {
            "implementation": "KeywordScopeGuard",
            "version": self.version,
            "is_valid_query": accepted,
            "decision": "ACCEPT" if accepted else "REJECT",
            "category": category,
            "rule_score": round(score, 3),
            "latency_ms": round((time.perf_counter() - start) * 1000, 3),
            "reason": (
                "命中產品範圍關鍵字，可進入後續資料查詢；不代表資料足以回答。"
                if accepted else "未辨識到產業、擴廠、人力、就業法規或官方資料主題；請補充查詢範圍。"
            ),
        }


keyword_scope_guard = KeywordScopeGuard()
